const contentsTypes = {
  ADD_CONTENT_START: 'ADD_CONTENT_START',
  FETCH_CONTENTS_START: 'FETCH_CONTENTS_START',
  SET_CONTENTS: 'SET_CONTENTS',
  DELETE_CONTENT_START: 'DELETE_CONTENT_START',
  FETCH_CONTENT_START: 'FETCH_CONTENT_START',
  SET_CONTENT: 'SET_CONTENT'
};

export default contentsTypes;