const inquiresTypes = {
  ADD_INQUIRES_START: 'ADD_INQUIRES_START',
  FETCH_INQUIRES_START: 'FETCH_INQUIRES_START',
  SET_INQUIRES: 'SET_INQUIRES',
  DELETE_INQUIRE_START: 'DELETE_INQUIRE_START',
  SET_INQUIRE: 'SET_INQUIRE',
  FETCH_INQUIRE_START: 'FETCH_INQUIRE_START',
};

export default inquiresTypes;