const InquiresComments = {
 ADD_INQUIRESCOMMENTS: 'ADD_INQUIRESCOMMENTS',
 FETCH_INQUIRESCOMMENTS: 'FETCH_INQUIRESCOMMENTS',
 SET_INQUIRESCOMMENTS: 'SET_INQUIRESCOMMENTS',
 DELETE_INQUIRESCOMMENTS: 'DELETE_INQUIRESCOMMENTS',
 EDIT_INQUIRESCOMMENTS: 'EDIT_INQUIRESCOMMENTS'
};

export default InquiresComments;