const InquireCommentsTypes = {
  ADD_INQUIRECOMMENTS: 'ADD_INQUIRECOMMENTS',
  FETCH_INQUIRECOMMENTS: 'FETCH_INQUIRECOMMENTS',
  SET_INQUIRECOMMENTS: 'SET_INQUIRECOMMENTS',
  // DELETE_INQUIRESCOMMENTS: 'DELETE_INQUIRESCOMMENTS',
  // EDIT_INQUIRESCOMMENTS: 'EDIT_INQUIRESCOMMENTS' 
};

export default InquireCommentsTypes;