const InquireCommentsTypes = {
  ADD_INQUIRECOMMENTS: 'ADD_INQUIRECOMMENTS',
  FETCH_INQUIRECOMMENTS: 'FETCH_INQUIRECOMMENTS',
  SET_INQUIRECOMMENTS: 'SET_INQUIRECOMMENTS',
  DELETE_INQUIRESCOMMENTS: 'DELETE_INQUIRESCOMMENTS',
  FETCH_INQUIRECOMMENT: 'FETCH_INQUIRECOMMENT',
  SET_INQUIRECOMMENT: 'SET_INQUIRECOMMENT'
  // EDIT_INQUIRESCOMMENTS: 'EDIT_INQUIRESCOMMENTS' 
};

export default InquireCommentsTypes;